import XCTest
@testable import Kalakello

/// The golden vectors in GoldenVectors.swift were generated by running the ORIGINAL
/// FastFishing JavaScript (fishing-advice.js) — so these tests prove the Swift port
/// scores and ranks exactly like the web app does.
final class ScoringTests: XCTestCase {

    func testGoldenScoresMatchWebApp() {
        XCTAssertFalse(goldenCases.isEmpty)
        for (i, c) in goldenCases.enumerated() {
            let species = Species(rawValue: c.species)!
            let cond = Conditions(temp: c.temp, pressure: c.pressure, pressure6hAgo: c.p6,
                                  wind: c.wind, cloud: c.cloud, hour: c.hour, light: nil)
            XCTAssertEqual(FishingScore.score(cond, species: species), c.expected, "golden case #\(i)")
        }
    }

    func testGoldenWindowsMatchWebApp() {
        let hours = goldenSeries.map { g in
            HourPoint(timestamp: Date(timeIntervalSince1970: g.t), temp: g.temp, pressure: g.pressure,
                      wind: g.wind, cloud: g.cloud, pressure6hAgo: g.p6, hour: g.hour, light: nil)
        }
        for g in goldenWindows {
            let result = WindowRanker.rank(hours, species: Species(rawValue: g.species)!,
                                           windowHours: g.hours, limit: 3, period: DayPeriod(rawValue: g.period)!)
            XCTAssertEqual(result.count, g.expected.count, "\(g.species) window count")
            for (a, b) in zip(result, g.expected) {
                XCTAssertEqual(a.start.timeIntervalSince1970, b.start, accuracy: 0.5, "\(g.species) start")
                XCTAssertEqual(a.score, b.score, "\(g.species) score")
            }
        }
    }

    func testInvalidInputReturnsNil() {
        let bad = Conditions(temp: 10, pressure: 1010, pressure6hAgo: nil, wind: -1, cloud: 50, hour: 12, light: nil)
        XCTAssertNil(FishingScore.score(bad, species: .kuha))
        let badCloud = Conditions(temp: 10, pressure: 1010, pressure6hAgo: nil, wind: 3, cloud: 120, hour: 12, light: nil)
        XCTAssertNil(FishingScore.score(badCloud, species: .hauki))
    }

    func testBandsAndCalibrationCap() {
        XCTAssertEqual(FishingScore.calibrate(100), 91)
        XCTAssertLessThanOrEqual(FishingScore.calibrate(100), 94)
        XCTAssertEqual(FishingScore.band(86), .exceptional)
        XCTAssertEqual(FishingScore.band(72), .veryGood)
        XCTAssertEqual(FishingScore.band(56), .good)
        XCTAssertEqual(FishingScore.band(40), .fair)
        XCTAssertEqual(FishingScore.band(39), .poor)
    }

    func testLightPhaseChangesScore() {
        func score(_ light: LightPhase) -> Int? {
            let c = Conditions(temp: 12, pressure: 1010, pressure6hAgo: 1011, wind: 3, cloud: 50, hour: 13, light: light)
            return FishingScore.score(c, species: .ahven)
        }
        XCTAssertGreaterThan(score(.twilight)!, score(.day)!)
        XCTAssertGreaterThan(score(.night)!, score(.day)!)
    }
}

final class ForecastParserTests: XCTestCase {

    private func json(windNullAt: Int? = nil) throws -> Data {
        let base = 1_760_000_400.0 // aligned to a full hour
        let n = 10
        let times = (0..<n).map { base + Double($0) * 3600 }
        var wind: [Any] = (0..<n).map { _ in 3.0 }
        if let i = windNullAt { wind[i] = NSNull() }
        let obj: [String: Any] = [
            "timezone": "Europe/Helsinki",
            "hourly": [
                "time": times,
                "temperature_2m": (0..<n).map { 10.0 + Double($0) },
                "pressure_msl": (0..<n).map { 1010.0 - Double($0) },
                "wind_speed_10m": wind,
                "cloud_cover": (0..<n).map { _ in 40.0 }
            ],
            "daily": [
                "time": [base - 4 * 3600],
                "sunrise": [base + 2 * 3600],
                "sunset": [base + 15 * 3600]
            ]
        ]
        return try JSONSerialization.data(withJSONObject: obj)
    }

    func testIncompleteHourIsDroppedNotZeroed() throws {
        let f = try ForecastParser.parse(try json(windNullAt: 2))
        XCTAssertEqual(f.hours.count, 9)
        XCTAssertFalse(f.hours.contains { $0.timestamp.timeIntervalSince1970 == 1_760_000_400 + 2 * 3600 })
    }

    func testPressureSixHoursAgo() throws {
        let f = try ForecastParser.parse(try json())
        XCTAssertNil(f.hours[5].pressure6hAgo)
        XCTAssertEqual(f.hours[7].pressure6hAgo ?? 0, 1010 - 1, accuracy: 0.001)
        XCTAssertEqual(f.hours[7].pressureDelta ?? 0, -6, accuracy: 0.001)
    }

    func testLightPhasesFromSunTimes() throws {
        let f = try ForecastParser.parse(try json())
        // sunrise is at +2 h, sunset at +15 h.
        // hour 0 = before the dawn window -> night; hour 3 = dawn window -> twilight; hour 7 = mid-day -> day.
        XCTAssertEqual(f.hours[0].light, .night)
        XCTAssertEqual(f.hours[3].light, .twilight)
        XCTAssertEqual(f.hours[7].light, .day)
    }

    func testGarbageThrows() {
        XCTAssertThrowsError(try ForecastParser.parse(Data("nope".utf8)))
    }
}

final class MoonTests: XCTestCase {
    func testKnownPhases() {
        let newMoon = Date(timeIntervalSince1970: 1_704_974_400)   // 2024-01-11 12:00 UTC
        let fullMoon = Date(timeIntervalSince1970: 1_706_184_000)  // 2024-01-25 12:00 UTC
        XCTAssertEqual(Moon.phase(at: newMoon).name, "Uusikuu")
        XCTAssertEqual(Moon.phase(at: fullMoon).name, "Täysikuu")
        XCTAssertGreaterThan(Moon.phase(at: fullMoon).illumination, 0.95)
    }
}

final class InsightsTests: XCTestCase {
    func testSimilarityHighForTypicalAndLowForOutlier() {
        let samples = (0..<8).map { i in
            CatchSample(temp: 12 + Double(i % 3), wind: 3 + Double(i % 2), cloud: 60, pressureDelta: -1.5, hour: 6, score: 75)
        }
        let insights = PersonalInsights.make(from: samples)!
        let typical = Conditions(temp: 13, pressure: 1010, pressure6hAgo: 1011.5, wind: 3.5, cloud: 60, hour: 6, light: nil)
        let outlier = Conditions(temp: 28, pressure: 1030, pressure6hAgo: 1024, wind: 12, cloud: 0, hour: 14, light: nil)
        XCTAssertGreaterThan(insights.similarity(to: typical) ?? 0, 0.7)
        XCTAssertLessThan(insights.similarity(to: outlier) ?? 1, 0.05)
    }

    func testNeedsMinimumSamples() {
        let few = [CatchSample(temp: 10, wind: 3, cloud: 50, pressureDelta: nil, hour: 7, score: 60)]
        XCTAssertNil(PersonalInsights.make(from: few))
    }
}
